// DRAFT — pending Member 3 API schema
// These types represent the frontend's best guess at the data shapes.
// Field names, nesting, and response envelopes WILL change once
// Member 3 publishes the OpenAPI schema.

/** Processing status for a saved page (from backend). */
export type PageStatus =
  | "captured"
  | "queued"
  | "discovered"
  | "extracting"
  | "extracted"
  | "processing"
  | "ready"
  | "extraction_failed"
  | "processing_failed";

/** A persisted research page returned by the backend API. */
export interface SavedPage {
  /** Stable page ID assigned by the backend. */
  id: string;
  /** Canonical URL after normalization. */
  canonicalUrl: string;
  /** Page title at time of capture. */
  title: string;
  /** Source domain extracted from the URL. */
  sourceDomain: string;
  /** Current processing status. */
  status: PageStatus;
  /** ISO 8601 timestamp of when the page was first captured. */
  capturedAt: string;
}

/** A workspace containing saved pages and (later) notes, tags, groups. */
export interface Workspace {
  id: string;
  name: string;
}

// ─── Extension ↔ Dashboard messaging ────────────────────────────

/** Error codes the extension can report for a failed capture attempt. */
export type CollectionErrorCode =
  | "ineligible_scheme"
  | "permission_denied"
  | "network_error"
  | "extraction_failed";

/** Status of a single collection attempt from the extension. */
export type CollectionEventStatus = "pending" | "sent_to_backend" | "failed";

/**
 * DRAFT — proposed CollectionEvent from extension to dashboard.
 * This is NOT a backend API type. It lives in extension-to-dashboard messaging.
 * Needs Member 2 sign-off on shape.
 */
export interface CollectionEvent {
  /** Unique per attempt, generated by extension. */
  eventId: string;
  /** Browser tab ID (ephemeral). */
  tabId: number;
  /** Attempted URL. */
  url: string;
  /** Tab title if available. */
  title: string | null;
  /** ISO 8601 timestamp. */
  timestamp: string;
  /** Current status of this collection attempt. */
  status: CollectionEventStatus;
  /** Set when status is 'failed'. */
  errorCode?: CollectionErrorCode;
  /** Human-readable error detail for debugging. */
  errorDetail?: string;
  /** Set by extension once backend confirms ingestion. Links to SavedPage.id. */
  pageId?: string;
}

// ─── Tracking state machine ──────────────────────────────────────

/**
 * Five-state machine for tracking indicator.
 * The indicator reflects confirmed extension state, never the dashboard's intent.
 */
export type TrackingState =
  | "paused"
  | "starting"
  | "active"
  | "stopping"
  | "unavailable";

// ─── Navigation views ────────────────────────────────────────────

export type DashboardView = "collection" | "graph" | "search" | "export";

// ─── Graph models ────────────────────────────────────────────────

export type EdgeType =
  | "related_to"
  | "source_of"
  | "answers"
  | "supports"
  | "references"
  | "navigated_to"
  | "duplicate_of"
  | "custom";

export interface GraphEdge {
  id: string;
  source: string;
  target: string;
  type: EdgeType;
  label: string | null;
  origin: "manual" | "suggested";
  status: "suggested" | "accepted" | "rejected";
  confidence?: number | null;
  evidence?: string | null;
  updatedAt?: string;
}

export interface GraphPage extends SavedPage {
  pos?: { x: number; y: number } | null;
  summary?: string | null;
  importance?: number | null;
  tabOpen?: boolean;
  group_ids?: string[];
}

export interface GraphSnapshot {
  workspace: Workspace;
  pages: GraphPage[];
  edges: GraphEdge[];
  seq?: number;
}
